import jsPDF from "jspdf";

/* ================= TYPES ================= */

export type ExpensePdfData = {
  expenseId: string;
  date: string; // ISO YYYY-MM-DD
  description: string;
  category: string;

  subtotal: number;
  vatPercent: number;
  vatAmount: number;
  total: number;

  status: "paid" | "pending" | "overdue" | "scheduled";
  notes?: string;
};

export type BusinessPdfData = {
  name: string;
  email?: string;
  address?: string;
};

export type GenerateExpensePdfParams = {
  expense: ExpensePdfData;
  business: BusinessPdfData;
};

/* ================= CONSTANT LABELS (EN ONLY) ================= */

const T = {
  title: "Expense",
  business: "Business information",
  details: "Expense details",
  description: "Description",
  category: "Category",
  date: "Date",
  status: "Status",
  totals: "Totals",
  subtotal: "Subtotal",
  vat: "VAT",
  total: "Total",
  notes: "Notes",
} as const;

/* ================= HELPERS ================= */

const eur = (n: number): string => `€${n.toFixed(2)}`;

const formatDate = (iso: string): string =>
  new Date(iso).toLocaleDateString("en-GB");

/* ================= MAIN ================= */

export async function generateExpensePdf({
  expense,
  business,
}: GenerateExpensePdfParams): Promise<Blob> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  let y = 20;

  /* ===== HEADER ===== */
  doc.setFontSize(22);
  doc.text(T.title, 14, y);

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(expense.expenseId, 196, y, { align: "right" });

  y += 6;
  doc.setDrawColor(200);
  doc.line(14, y, 196, y);
  y += 10;

  /* ===== BUSINESS CARD ===== */
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.text(T.business, 14, y);
  y += 4;

  doc.setDrawColor(220);
  doc.roundedRect(14, y, 82, 24, 3, 3);

  doc.setFontSize(10);
  doc.text(business.name, 18, y + 6);

  if (business.email) {
    doc.text(business.email, 18, y + 12);
  }

  if (business.address) {
    doc.text(business.address, 18, y + 18, { maxWidth: 74 });
  }

  /* ===== DETAILS ===== */
  y += 32;
  doc.setFontSize(12);
  doc.text(T.details, 14, y);
  y += 6;

  doc.setFontSize(10);
  doc.text(`${T.date}: ${formatDate(expense.date)}`, 14, y);
  doc.text(`${T.status}: ${expense.status.toUpperCase()}`, 120, y);

  y += 5;
  doc.text(`${T.category}: ${expense.category}`, 14, y);

  /* ===== DESCRIPTION ===== */
  y += 10;
  doc.setFontSize(11);
  doc.text(T.description, 14, y);
  y += 5;

  doc.setFontSize(10);
  doc.text(expense.description || "-", 14, y, { maxWidth: 180 });
  y += 14;

  /* ===== TOTALS BOX ===== */
  doc.setFontSize(12);
  doc.text(T.totals, 120, y);
  y += 6;

  doc.setFontSize(10);
  doc.text(T.subtotal, 120, y);
  doc.text(eur(expense.subtotal), 196, y, { align: "right" });
  y += 5;

  doc.text(`${T.vat} (${expense.vatPercent}%)`, 120, y);
  doc.text(eur(expense.vatAmount), 196, y, { align: "right" });
  y += 5;

  doc.setDrawColor(150);
  doc.line(120, y, 196, y);
  y += 5;

  doc.setFontSize(11);
  doc.text(T.total, 120, y);
  doc.text(eur(expense.total), 196, y, { align: "right" });

  /* ===== NOTES ===== */
  if (expense.notes) {
    y += 14;
    doc.setFontSize(12);
    doc.text(T.notes, 14, y);
    y += 5;

    doc.setFontSize(10);
    doc.text(expense.notes, 14, y, { maxWidth: 180 });
  }

  /* ===== FOOTER ===== */
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by SmartWerk", 14, 287);

  return doc.output("blob");
}