// app/dashboard/analytics/bookkeeper/utils/exportAnalyticsPDF.ts

import { jsPDF } from "jspdf";
import type { AnalyticsStats } from "../types";

const eur = (n: number) =>
  `€${n.toLocaleString("nl-NL", {
    minimumFractionDigits: 2,
  })}`;

export function exportAnalyticsPDF(
  stats: AnalyticsStats,
  scopeLabel: string,
  periodLabel: string
) {
  const doc = new jsPDF();

  let y = 20;

  /* ===== HEADER ===== */

  doc.setFontSize(18);
  doc.text("Analytics Report", 14, y);
  y += 10;

  doc.setFontSize(11);
  doc.text(`Scope: ${scopeLabel}`, 14, y);
  y += 6;

  doc.text(`Period: ${periodLabel}`, 14, y);
  y += 6;

  doc.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    14,
    y
  );
  y += 10;

  /* ===== DIVIDER ===== */
  doc.line(14, y, 196, y);
  y += 10;

  /* ===== STATS ===== */

  doc.setFontSize(13);
  doc.text("Financial Summary", 14, y);
  y += 8;

  doc.setFontSize(11);

  const rows = [
    ["Total Income", eur(stats.income)],
    ["Total Expenses", eur(stats.expense)],
    ["Net Profit", eur(stats.profit)],
    ["Total VAT", eur(stats.vat)],
  ];

  rows.forEach(([label, value]) => {
    doc.text(label, 14, y);
    doc.text(value, 150, y, { align: "right" });
    y += 7;
  });

  /* ===== FOOTER ===== */

  y += 10;
  doc.line(14, y, 196, y);
  y += 8;

  doc.setFontSize(9);
  doc.text(
    "Generated by SmartWerk Analytics",
    14,
    y
  );

  /* ===== SAVE ===== */

  const safeScope = scopeLabel
    .replace(/[^a-z0-9]/gi, "_")
    .toLowerCase();

  doc.save(
    `analytics-${safeScope}-${new Date()
      .toISOString()
      .slice(0, 10)}.pdf`
  );
}